name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare deps
      run: sudo apt install -y meson ninja-build pkg-config libpng-dev libfreetype-dev libgl-dev libegl-dev libglew-dev libwayland-dev libxkbcommon-dev wayland-protocols libgles2-mesa-dev
    - name: configure
      run: meson setup build --buildtype=debug -Db_sanitize=address -Db_lundef=false
    - name: make
      run: ninja -C build
    - name: make check
      run: cd build && meson test
